### ISSUE TITLE
CITATION file

### ISSUE THREAD

**Issue by drvinceknight** [baharev/sdopt-tearing#1]
I am currently part of a group of people writing a paper on testing for research software, as your code uses property based test (hypothesis) I would like to reference it. Have you thought about adding a citation file?

Details here: http://www.software.ac.uk/blog/2013-09-02-encouraging-citation-software-introducing-citation-files

Example here: https://github.com/dib-lab/khmer/blob/master/CITATION

Thanks!

**Comment by baharev** [comment]
Thank you very much for drawing my attention to this issue. I did not know about the CITATION file. Please check:

https://github.com/baharev/sdopt-tearing/blob/master/CITATION

Note that these manuscripts have only been submitted and have not been accepted yet. Please also note that the code is a work in progress, and I am not ready for cooperation yet.

Are you also interested in my experience with property-based testing? Or can I help your research any further regarding property-based testing? We could also discuss this on Skype, for example.

**Comment by drvinceknight** [comment]
Sorry for the late reply @baharev! 

Citation file looks fantastic!

> Are you also interested in my experience with property-based testing? Or can I help your research any further regarding property-based testing? We could also discuss this on Skype, for example.

I don't think that's necessary just yet. I'm one of a few who started writing a paper on testing for research software (as a hackday project for http://www.software.ac.uk/cw16). I'm writing a section on property based tests (hypothesis) and mainly wanted to reference software that made use of it. You can see the work in progress here: http://vknight.org/TestingPaper/. (Still very much early stages.)

**Comment by baharev** [comment]
OK, thanks again for drawing my attention to this CITATION file. If there is anything I can help you with regarding property-based testing, please let me know. I have some experience with it, and I see it's strengths and weaknesses.

**Comment by drvinceknight** [comment]
> I have some experience with it, and I see it's strengths and weaknesses.

That sounds fantastic. Once the manuscript is in better shape it would be great to have your thoughts: it started with a lot of enthusiasm during the hack day, no doubt it'll take a little while for progress to start up again.
