### ISSUE TITLE
Any backend for Julia in perspective yet ?

### ISSUE THREAD

**Issue by o314** [baharev/sdopt-tearing#4]
Hello Ali,

Thanks first for providing us freely this codebase on the very specific subject of tearing.

I have seen there is some backend for AMPL, and Python.

I would like to know if it has been envisaged already to target the [Julia](http://julialang.org/) language?
It's taking more and more place in the mathematical landscape.

FYI, the networkx package has been ported to [lightgraphs.jl](https://github.com/JuliaGraphs/LightGraphs.jl).

Cordially
Olivier

**Comment by baharev** [comment]
Hi Olivier,

No, I have no plans for a Julia port, sorry.

Ali
